Site\SiteBundle\Entity\Categories:
    type: entity
    table: categories
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
